pipeline {
    agent any
    
    environment {
		DOCKERHUB_CREDENTIALS=credentials('docker_password')
	}

    stages {
        stage('build application') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'devopshint', url: 'https://github.com/amoldeshpande05/calculator-asset']]])
            }
        }
        
        stage('build docker Image') {
            steps {
               sh 'docker build -t amoldeshpande/calculator-v1 .'
            }
        }
        
        stage('Push Docker Image') {
            steps {
                sh "echo $DOCKERHUB_CREDENTIALS_PSW | docker login --username amoldeshpande --password-stdin"
                sh "docker push amoldeshpande/calculator-v1"
            }
        }
        
        stage('Deploying to kubernates preparation') {
            steps {
                sh 'curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl'
                sh 'chmod +x ./kubectl && mv kubectl /usr/local/sbin'
            }
        }
        stage('Deploy to kubernates') {
            steps {
                sh 'chmod +x ./kubectl && mv kubectl /usr/local/sbin'
            }
        }
        
    }
    post {
		always {
			sh 'docker logout'
			sh 'echo Completed!'
		}
	}
}
