kind: Deployment
apiVersion: apps/v1
metadata:
  name: playground-ui-dev-home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground-ui-dev-home
  template:
    metadata:
      labels:
        app: playground-ui-dev-home
    spec:
      containers:
        - name: playground-ui-dev-home
          image: docker.io/amoldeshpande/playground-ui-dev-home
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: playground-ui-dev-home-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: playground-ui-dev-home